# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Ado-Test/GitTemplates'
    ref: master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "git leaks"
    jobs:
      - job: "GitLeaks"
        steps:
        - checkout: self
        - template: templates/homebrew.yml@templates
        - template: templates/gitleaks.yml@templates
        - template: templates/json-lint.yml@templates

  - stage: "Build Java"
    jobs:
      - job: " Build Java project"
        steps:
        
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
